// Skeleton generated by Hyland Unity Editor on 3/17/2021 12:18:40 AM
namespace testam
{
    using System;
    using System.Text;
    using Hyland.Unity;
    using Hyland.Unity.CodeAnalysis;
    using Hyland.Unity.Workflow;
	using System.IO;
	using System.Data;
	using System.Data.SqlClient;
    
    
    /// <summary>
    /// testam
    /// </summary>
    public class testam2 : Hyland.Unity.IWorkflowScript
    {

		Application _app = null;
		string sConnectTM = string.Empty;
		string explantaion = string.Empty;
		string FaxLine = string.Empty;
		string sFaxServer = string.Empty;
		string sJID = string.Empty;
		string pages = string.Empty;
		string ssPecipient = string.Empty;
		string sXmitResult = string.Empty;
		string sRetryCt = string.Empty;
		string sStatusCd = string.Empty;
		string sSubject = string.Empty;
		string sTransmitTm = string.Empty;
		string sUID = string.Empty;
		string sSubjectRGHID = string.Empty;
		string sSubjectRGHType = string.Empty;
		string sFailSuccess = string.Empty;
		
        #region IWorkflowScript
        /// <summary>
        /// Implementation of <see cref="IWorkflowScript.OnWorkflowScriptExecute" />.
        /// <seealso cref="IWorkflowScript" />
        /// </summary>
        /// <param name="app"></param>
        /// <param name="args"></param>
        public void OnWorkflowScriptExecute(Hyland.Unity.Application app, Hyland.Unity.WorkflowEventArgs args)
        {
            
			try
			{
				string sFilePath = FirstPage.SubPath();
				string sFilePath = @"\\Cardinalhealth.net\applications\EC500\ONB\PRD_SYS\Diskgroups\EP" + FsilePath ;
				using(StreamReader reader = new StreamReader(sFilePath))
				{
					int linect = 0;
					while(!reader.EndOfStream)
					{
						string line = reader.ReadLine();
						linect++;
						if(line.ToUpper().Contains("RECIPIENT AT"))
						{
							string[] splitCell = line.Split(new[]{"at "}, StringSplitOptions.RemoveEmptyEntries);
							string strCell = splitCell[1];
							string strRecipient = strCell;
						}
						if(line.ToUpper().Contains("SUBJECT:"))
						{
							if(line.ToUpper().Contains("FAX:"))
							{
								string[] splitCell = line.Split(new[]{":"}, StringSplitOptions.RemoveEmptyEntries);
								string strCell = splitCell[1];
								string strRecipient = strCell;
							}
						}
					}
				}
				
				
			}
			catch(Exception ex)
			{
				app.Diagnostics.Write(ex);
			}
			
			
        }
		
		private void ModifyKeywordInCurrentDocument(Document doc, string keywordType, string keywordValue)
		{
			using(DocumentLock documentLock = doc.LockDocument())
			{
				if(documentLock.Status == DocumentLockStatus.LockObtained)
				{
					KeywordModifier keymod = doc.CreateKeywordModifier();
					KeywordType keyType = _app.Core.KeywordTypes.Find(keywordType);
					if(keyType == null)
					{
						keymod.AddKeyword(keywordType,keywordValue);		
						
					}
					else
					{
						KeywordRecord keyRec = doc.KeywordRecords.Find(keyType);
						KeywordRecordType keyRecType = keyRec.KeywordRecordType;			
						
						Keyword newKeyword = keyType.CreateKeyword(keywordValue);
						
						if(keyRecType.RecordType== RecordType.MultiInstance)
						{
							EditableKeywordRecord editKeyRec = keyRec.CreateEditableKeywordRecord();
							Keyword keyword = editKeyRec.Keywords.Find(keywordType);
							if(keyword != null)
							{
								editKeyRec.UpdateKeyword(keyword, newKeyword);
							}
							else
							{
								editKeyRec.AddKeyword(keywordType, keywordValue);
							}
							
							keymod.AddKeywordRecord(editKeyRec);
							
						}
						else
						{
							Keyword keyword = keyRec.Keywords.Find(keywordType);
							if(keyword!=null)
								keymod.UpdateKeyword(keyword, newKeyword);
							else
								keymod.AddKeyword(keywordType, keywordValue);
						}
					}
					keymod.ApplyChanges();					
				}
			}
		}
		private void SetKeywordValues(Document document)
		{
			try
		   	{
		   		foreach(KeywordRecord keywordRecord in document.KeywordRecords)
		        {
		        	foreach(Keyword keyword in keywordRecord.Keywords)
		            {
		            	switch (keyword.KeywordType.Name)
		                {
									                    
						}
					}
				}
		   }
		   catch(Exception ex)
		   {
		   		_app.Diagnostics.Write(ex);
		   }
		}
		
        #endregion
    }
}
